nf-core/smrnaseq

- .travis.yml
- README.md
- conf/test.config
- environment.yml
- main.nf
- nextflow.config
Continued work from @apeltzer's PR #1 
WIP: still testing, docker builds are getting slow locally so I thought I'd push.
> Travis testing, continued work on conda deps

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/markdownlint.yml
- CHANGELOG.md
- Dockerfile
- environment.yml
Hi,
To have the docker up-to-date so I can test better the pipeline, I am updating the tools and dockerfile.
I added as well the github templates to have it for next time.
Let me know if this sounds good.
> Update tools and Dockerfile/Singularity

- CHANGELOG.md
- environment.yml
Adding mirtop and razers3 to update the alignment step to precursors with these tools.
> add new tools to environment

- CHANGELOG.md
- environment.yml
this need to be fixed, to get the test running. TEMPLATE testing is failing due to that right now in local using the docker container.
> fix multiqc error

- CHANGELOG.md
- environment.yml
after `nf-core lint` many packages needed update, so doing this to have a recent release soon.
> update all tools to latest

- .travis.yml
- Dockerfile
- environment.yml
- nextflow.config
Bump devel version to prepare it for release. I am not sure how to update dev, but I guess you will let me know if this is not the way.
> bump dev version

- main.nf
Last comments for release revision. Thanks @drpatelh
> fix genome parameter help and typo for summary variable

- CHANGELOG.md
- environment.yml
I am updating with the new TEMPLATE and some packages are missing.
test will fail but the new docker is needed to move forward.
> update docker with new packages to migrate to new template

- .github/workflows/awsfulltest.yml
- .github/workflows/awstest.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- conf/igenomes.config
- conf/test.config
- conf/test_full.config
- main.nf
- nextflow.config
- nextflow_schema.json
Setting up full size dataset testing - see #56
> Add s3 data paths to test_full.config

- CHANGELOG.md
- bin/edgeR_miRBase.r
- main.nf
Fixing:
* error when running 1 samples: https://github.com/nf-core/smrnaseq/issues/31
* use custom genome: https://github.com/nf-core/smrnaseq/pull/63
**Learn more about contributing:** https://github.com/nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md
> Use custom genome and fix nt in FASTA

- CHANGELOG.md
Updated the changelog so that duplicate releases before v1.0.0 are removed; fixes nf-core/smrnaseq#37
**Learn more about contributing:** https://github.com/nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md
> Removed reference to releases before v1.0.0 and added headings for added changes

- CHANGELOG.md
- nextflow_schema.json
Otherwise parameter validation complains
> added custom into protocol enum

- .nf-core-lint.yml
- lib/NfcoreSchema.groovy
- main.nf
- nextflow.config
removed some genome parameters from `nextflow.config` again
> removed genome parameters

- conf/modules.config
Update publishDir mode to use the publish_dir_mode parameter.
> Update publishDir mode

- CHANGELOG.md
- modules/local/datatable_merge.nf
- modules/local/mirtop_quant.nf
Bump mirtop version 0.4.25 to fix the problem with its log being changed and multiqc giving an exception see https://github.com/nf-core/smrnaseq/issues/137
> Bump mirtop version 0.4.25

- .github/workflows/awsfulltest.yml
- .github/workflows/awstest.yml
- .github/workflows/branch.yml
- .github/workflows/fix-linting.yml
- .github/workflows/linting.yml
- .prettierignore
- README.md
- assets/email_template.html
- bin/check_samplesheet.py
- nextflow.config
Merging template after the release of tools version 2.4.0
> Merging template 2.4.0

- CHANGELOG.md
- modules/local/mirdeep2_mapper.nf
- modules/local/mirdeep2_run.nf
> Fix linting

- CHANGELOG.md
- conf/modules.config
- docs/output.md
This should address the issue that @gpalidwor observed a couple of days ago in #161.
> Bugfix for #161

- CHANGELOG.md
- modules.json
- modules/nf-core/modules/cat/fastq/main.nf
- modules/nf-core/modules/multiqc/main.nf
- modules/nf-core/modules/multiqc/meta.yml
- modules/nf-core/modules/samtools/flagstat/main.nf
- modules/nf-core/modules/samtools/idxstats/main.nf
- modules/nf-core/modules/samtools/index/main.nf
- modules/nf-core/modules/samtools/sort/main.nf
- modules/nf-core/modules/samtools/stats/main.nf
- modules/nf-core/modules/trimgalore/main.nf
- modules/nf-core/modules/trimgalore/meta.yml
- workflows/smrnaseq.nf
This should adress #137 for real ;-) 
Basically just an update of all modules in the pipeline for the dev version with `nf-core modules update` - hopefully should now be fine 👍🏻
> Fix for MultiQC issues (MQC 1.13dev)

- CHANGELOG.md
- modules/local/bowtie_map_contaminants.nf
- modules/local/bowtie_map_mirna.nf
This PR improved index handling following the approach defined in nf-core/modules and the respective bowtie modules there. 
As suggested by @drpatelh on slack ;-)
> Improve bt index handling

- docs/usage.md
Not even worth to mention in changelog I think ...
> Tiny typo fix

- README.md
> Fix extra/outdated zenodo shield in README.md

- modules.json
- modules/nf-core/modules/cat/fastq/main.nf
- modules/nf-core/modules/custom/dumpsoftwareversions/main.nf
- modules/nf-core/modules/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
- modules/nf-core/modules/multiqc/main.nf
- modules/nf-core/modules/multiqc/meta.yml
- modules/nf-core/modules/samtools/flagstat/main.nf
- modules/nf-core/modules/samtools/stats/main.nf
- workflows/smrnaseq.nf
No text required, all in the description ;-)
> Update Modules (e.g. MQC 1.13 final, bugfix for mirtop)

- tower.yml
Defined basic figures and reports via tower.yml so that summary outputs can be viewed in Nextflow Tower.
> Add support for Nextflow Tower reports.

- docs/usage.md
This smallRNA workflow throws away any reads provided as input, but this was not documented. Fixes that
> Document that the pipeline forces single-end analysis

- docs/usage.md
- nextflow.config
> Fix-emillers-comments

- CHANGELOG.md
- nextflow.config
> Bump dev branch

- CHANGELOG.md
- modules/local/parse_fasta_mirna.nf
> [FIX] - Sed uses a separator not working fine on all operating systems - conda failure fix for osx

- CHANGELOG.md
- muchasmuchasgracias/pipeline_info/execution_trace_2022-12-02_14-28-46.txt
- workflows/smrnaseq.nf
> [FIX] Fixes mirtrace report to be across all samples instead of only one

- CHANGELOG.md
- nextflow.config
> Prepare 2.2.1 release

- modules/local/bowtie_genome.nf
- modules/local/bowtie_mirna.nf
- modules/local/format_fasta_mirna.nf
- modules/local/mirdeep2_run.nf
- modules/local/parse_fasta_mirna.nf
- subworkflows/local/genome_quant.nf
- subworkflows/local/mirna_quant.nf
- workflows/smrnaseq.nf
> Attempt at introducing meta2 everywhere

- CHANGELOG.md
- modules.json
- modules/nf-core/fastp/tests/main.nf.test
- modules/nf-core/fastqc/tests/main.nf.test
- modules/nf-core/fastqc/tests/main.nf.test.snap
- modules/nf-core/umicollapse/main.nf
- modules/nf-core/umicollapse/tests/main.nf.test
- modules/nf-core/umicollapse/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test
> Bump the modules one last time

- CHANGELOG.md
- modules.json
- modules/nf-core/cat/cat/tests/main.nf.test
- modules/nf-core/cat/cat/tests/main.nf.test.snap
- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> Upgrade MQC 1.21

- CHANGELOG.md
- modules.json
- modules/local/mirtrace.nf
- modules/nf-core/samtools/sort/main.nf
- modules/nf-core/samtools/sort/meta.yml
- modules/nf-core/samtools/sort/tests/main.nf.test
- modules/nf-core/samtools/sort/tests/main.nf.test.snap
- modules/nf-core/samtools/sort/tests/nextflow.config
- subworkflows/nf-core/bam_sort_stats_samtools/main.nf
> Fix mirtrace cast issue

- README.md
- modules.json
- modules/nf-core/fastp/main.nf
- modules/nf-core/fastp/tests/main.nf.test
- modules/nf-core/fastp/tests/main.nf.test.snap
- modules/nf-core/fastp/tests/nextflow.interleaved.config
- modules/nf-core/fastp/tests/nextflow.save_failed.config
- modules/nf-core/fastqc/main.nf
- modules/nf-core/umicollapse/tests/main.nf.test
- modules/nf-core/umicollapse/tests/main.nf.test.snap
- modules/nf-core/umitools/extract/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/nextflow.config
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/nextflow.save_trimmed.config
> Bump-modules

- modules/local/datatable_merge.nf
- modules/local/mirtop_quant.nf
Change conda channel from `conda-base` to `conda-forge`. 
Fixes #347.
> change conda channels

- CHANGELOG.md
- conf/test_full_filter_contamination.config
- modules/local/filter_stats.nf
- nextflow.config
Addressing
https://github.com/nf-core/smrnaseq/issues/360
> Fixed filter_stats issue and added profile for testing this

- CHANGELOG.md
- conf/modules.config
Fix for https://github.com/nf-core/smrnaseq/issues/404
> Fix Umicollapse PE wrong method set

- CHANGELOG.md
- modules.json
- modules/nf-core/mirtrace/qc/environment.yml
- modules/nf-core/mirtrace/qc/main.nf
- modules/nf-core/mirtrace/qc/meta.yml
- modules/nf-core/mirtrace/qc/tests/main.nf.test
- modules/nf-core/mirtrace/qc/tests/main.nf.test.snap
- tests/test_contamination_tech_reps.nf.test.snap
- tests/test_nextflex.nf.test
- tests/test_nextflex.nf.test.snap
- tests/test_skipfastp.nf.test.snap
- tests/test_umi.nf.test.snap
- workflows/smrnaseq.nf
> Add `config` mode to nf-core `mirtrace/qc`

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- nextflow.config
> Bump-minimum-nxf-version 

- README.md
> Add some more credits

- modules/local/edger_qc/tests/edger_qc.nf.test
- modules/local/edger_qc/tests/edger_qc.nf.test.snap
> Fix test edgeR

- CHANGELOG.md
- subworkflows/local/prepare_genome/main.nf
- tests/test_contamination_tech_reps.nf.test.snap
- tests/test_mirgenedb.nf.test.snap
- tests/test_nextflex.nf.test.snap
- tests/test_skipfastp.nf.test
- tests/test_skipfastp.nf.test.snap
- tests/test_umi.nf.test
- tests/test_umi.nf.test.snap
> Reorganize `clean fasta` code

- conf/protocol_cats.config
- conf/protocol_illumina.config
- conf/protocol_nextflex.config
- conf/protocol_qiaseq.config
- conf/test_full_filter_contamination.config
- conf/test_skipfastp.config
- docs/usage.md
- nextflow.config
- nextflow_schema.json
> Removed unused protocol argument and updated docs

- CHANGELOG.md
- modules.json
- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> Update-software-modules & xchangelog

- CHANGELOG.md
- workflows/smrnaseq.nf
Closes https://github.com/nf-core/smrnaseq/issues/496
> Converted ch_bowtie_index to value channel

- .gitignore
- CHANGELOG.md
- conf/modules.config
- modules.json
- modules/nf-core/mirtop/counts/environment.yml
- modules/nf-core/mirtop/counts/main.nf
- modules/nf-core/mirtop/counts/mirtop-counts.diff
- modules/nf-core/mirtop/export/environment.yml
- modules/nf-core/mirtop/export/main.nf
- modules/nf-core/mirtop/export/mirtop-export.diff
- modules/nf-core/mirtop/gff/environment.yml
- modules/nf-core/mirtop/gff/main.nf
- modules/nf-core/mirtop/gff/mirtop-gff.diff
- modules/nf-core/mirtop/stats/environment.yml
- modules/nf-core/mirtop/stats/main.nf
- modules/nf-core/mirtop/stats/mirtop-stats.diff
> Fix mirgenedb mirtop
