nf-core/smrnaseq

CHANGELOG.md
environment.yml

Update to last `mirtop` version to fix an important bug.
The docker builds correctly locally and it works with the open PR code I have.
Hopefully, after this, I can finish the PR and if we get test passes, we'll get a release soon!

fix mirtop version

---

main.nf
nextflow.config

Removed duplicate `mature` and `hairpin` parameters from `nextflow.config`
These are properly initialised to their default values a few lines down in the same file.

Remove duplicate parameters

---

bin/edgeR_miRBase.r
main.nf

This simple change speeds up the bowtie-build process.
I have added `--threads $(nproc)` to all `bowtie-build` commands.
- [x ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
**Learn more about contributing:** https://github.com/nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md

Speed up bowtie-build using multithreading

---

CHANGELOG.md
environment.yml
main.nf
nextflow.config
nextflow_schema.json

* added missing parameters ("unexpected") to `nextflow.config` and `nextflow_schema.json`
* removed the logging about `single_end` as that's the only supported configuration anway

cleaned up parameters

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
environment.yml
nextflow.config

bump version to 1.2.0dev

---

conf/test.config
conf/test_full.config
conf/test_no_genome.config
nextflow.config

The `samplesheet` files in the test-dataset repository have been moved to a new folder to allow its versioning see [here](https://github.com/nf-core/test-datasets/pull/402), as was discussed on #120

Samplesheet versioning

---

CHANGELOG.md
modules/local/seqcluster_collapse.nf

update seqcluster version from 1.2.8 to 1.2.9. New version of seqcluster fixes bug where UMI detection is mistakenly attempted

Fix seqcluster umi bug

---

CHANGELOG.md
README.md

In the last template merge (#148) the link to zenodo was broken, fixed here and also updated changelog

Fix zenodo link and update changelog

---

CHANGELOG.md
subworkflows/local/genome_quant.nf
workflows/smrnaseq.nf

Fixes #159 
The problem was that not all the index files were staged in the work dir, see #159 for more background.

Fix bug when --bowtie_indices is provided via the CLI

---

CHANGELOG.md
modules/local/mirtrace.nf
nextflow.config
nextflow_schema.json

This removes the `mirtrace_protocol` as it was redundant and apparently always set to `params.protocol` - issue  reported by @gpalidwor and fixed in this PR - see details in #168

Fix for #168

---

docs/usage.md
modules/local/mirtrace.nf
modules/local/trimgalore.nf

This should fix the inconsistencies between what is used in trimgalore and in mirtrace. Now keeps things the same.

Fix protocol consistency

---

bin/check_samplesheet.py
subworkflows/local/input_check.nf
workflows/smrnaseq.nf

In preparation for handling adapter sequences in the samplesheet, we now pass through all columns in the samplesheet as keys in the meta map.
The commit also removes a bunch of redundant fastq_2 checking which we don't use.

More flexible samplesheet handling

---

README.md
docs/usage.md
nextflow_schema.json

Joses comments resolved for release

---

CHANGELOG.md
modules/local/mirtrace.nf

The mirTrace module was using a series of regexes to pull out the fastq basename as a sample ID, rather than using $meta.id as for other tools in the pipeline

Fixed an issue where miRTrace reports fastq basename instead of sample ID

---

CHANGELOG.md
conf/modules.config
modules/local/mirtrace.nf
nextflow.config
nextflow_schema.json
subworkflows/local/fastqc_fastp.nf
subworkflows/local/mirtrace.nf
workflows/smrnaseq.nf

The important changes here are the removal of the skip_qc parameter (skip_fastp is still intact), and the more complicated work of running mirtrace more carefully.
The workflow can accomodate samples that use different adapter sequences, auto-detected by FastP. Unfortunately, each run of mitrace assumes a single adapter, so here we group samples by adapter and run mirtrace in batches by adapter. The grouping is helpful to ensure that samples that share an adapter can be grouped in the MultiQC report.

Skipqc fix and group samples by adapter for mirtrace

---

workflows/smrnaseq.nf

If params.filter_contamination is true, then pass in reads returned from CONTAMINANT_FILTER. Otherwise, use FASTQC_FASTP.out.reads.
Solves #238

Pass filtered or unfiltered reads to MIRNA_QUANT.

---

CHANGELOG.md
conf/public_aws_ecr.config

Remove globs from process definitions in ECR containers so aliased modules.

Remove glob from process definition when using ECR container

---

docs/usage.md
nextflow.config
nextflow_schema.json
workflows/smrnaseq.nf

Mirbase has changed where they host genoms, hairpin and mature fasta files. 
Previously: `https://mirbase.org/ftp/CURRENT/mature.fa.gz`
Updated: `https://mirbase.org/download/CURRENT/mature.fa`
Note that Mirbase no longer hosts the compressed version of these files - only the uncompressed fa version.

Update Mirbase URLs structure to match their new structure

---

assets/known_adapters.fa
conf/modules.config
modules.json
modules/nf-core/fastqc/tests/main.nf.test
modules/nf-core/fastqc/tests/main.nf.test.snap
modules/nf-core/umicollapse/main.nf
nextflow.config
nextflow_schema.json
subworkflows/local/mirna_quant.nf
subworkflows/local/mirtrace.nf
workflows/smrnaseq.nf

Fix the stacksize and pretty much everything else

---

conf/modules.config
conf/test.config
nextflow.config
nextflow_schema.json

This
- adds a new parameter `save_aligned` to specify whether to store aligned reads (of `GENOME_QUANT:BOWTIE_MAP_GENOME`)
- activates the already exisiting paramter `save_merged` 
- sets `save_aligned` to `false` for test profile

Add options for saving intermediate files

---

workflows/smrnaseq.nf

This adds a parameter check to make sure `--mirgenedb_species` is set once `--mirgenedb` is used. This should avoid cases like in #312  in the future.

add check if mirgene_db_species is set if mirgene_db

---

CHANGELOG.md
modules/local/bowtie_map_mirna.nf
modules/local/mirdeep2_run.nf

Fix reported bugs

---

CHANGELOG.md
modules/local/mirtrace.nf
subworkflows/local/mirtrace.nf

This addresses the staging / casting issue first identified in the issue https://github.com/nf-core/smrnaseq/issues/327
The previous fix ignored the possibility that (depending on the platform), directly referencing work directories can cause trouble as there is no guarantee that these are staged properly to the work dir of mirtrace. This is resolved by reverting to the previously working approach with mirtrace where the files are staged  to the same directory, then adding functionality to use the filename(s) of provided files in the work dir of mirtrace directly instead. This ensures nextflow is aware of any files being staged to mirtrace, thus guaranteeing that files are properly staged.

Fix mirtrace staging bug

---

CHANGELOG.md
conf/modules.config
docs/usage.md

Fixes #326. 
With this change it is possible to enable `fastp` adapter auto-detection using the parameter value "auto-detect".

Fix auto-detection of adapter with fastp

---

CHANGELOG.md
modules.json
modules/local/mirtop_quant.nf
subworkflows/nf-core/utils_nfcore_pipeline/main.nf

This fixes the conda env for the `mirtop_quant `process. The issue with `pysam` that is part of the env seems to be caused by the python version (3.6). Therefore, adding the python=3.7 dependency.
Related to #347.

Fix mirtop quant conda env

---

CHANGELOG.md
docs/usage.md

Updating doc to avoid the use of paired-data #332

fix docs for single end

---

CHANGELOG.md
nextflow.config
nextflow_schema.json

The PR addresses running the error that appears when running this command:
nextflow run ../../main.nf -profile test,docker --outdir results -resume
The issue is related to having the params protocol set to "Custom" while the MIRTRACE_RUN process expects "custom"
Related to this issue:
https://github.com/nf-core/smrnaseq/issues/371
https://github.com/nf-core/smrnaseq/issues/373

Default test profile causes pipeline failure

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
conf/test.config
conf/test_index.config
conf/test_no_genome.config
conf/test_umi.config

The CI tests are currently executed with the profile configuration `-profile test,illumina,docker`, which differs from the typical `-profile test,docker` that most nf-core pipelines use. If the users run the pipeline with `-profile test,docker` it would lead to the protocol `custom` to be used, instead of `illumina`. This inconsistency could lead to confusion, as the standard user environment does not accurately reflect the same results as the CI test environment.
This PR addresses #371.
Closes #375 
It improves README documentation regarding how to use the protocol profiles.  
It includes the `illumina` protocol profiles directly in the test profiles so that users can run them out-of-the-box as they do with any other nf-core pipeline:
`nextflow run nf-core/smrnaseq -profile test,docker …

Change profile configuration for CI tests 

---

CHANGELOG.md
conf/test_contamination.config
modules/local/blat_mirna/blat_mirna.nf
modules/local/blat_mirna/tests/blat_mirna.nf.test
modules/local/blat_mirna/tests/blat_mirna.nf.test.snap
nextflow.config
subworkflows/local/contaminant_filter.nf

This PR:
- Adds nf-test to track files obtained from local module `blat_mirna`. Useful for the future migration to an nf-core module.
- Adds a small pipeline contamination test.
- Fixes #354 by changing the quay container for a community wave container.

Add nf-test for local module `blat_mirna`

---

CHANGELOG.md
conf/test_nextflex.config
subworkflows/local/utils_nfcore_smrnaseq_pipeline/main.nf

Addresses https://github.com/nf-core/smrnaseq/issues/415

Fix paired end sample handling

---

CHANGELOG.md
conf/modules.config
docs/output.md

This PR:
- Removes automatic wrapping of fasta files by `seqkit replace`
- Corrects minor docs issues

Fix wrapping in fasta files

---

.gitignore
CITATIONS.md
nextflow.config
subworkflows/local/utils_nfcore_smrnaseq_pipeline/main.nf

Tiny bugfixes

---

nextflow_schema.json

Fix igenomes_base in nextflow_schema

---

CHANGELOG.md
bin/pivot_longer.R
bin/pivot_wider.R
conf/modules.config
modules/local/pivot/longer/environment.yml
modules/local/pivot/longer/main.nf
modules/local/pivot/wider/environment.yml
modules/local/pivot/wider/main.nf
subworkflows/local/mirna_quant.nf
tests/test_contamination_tech_reps.nf.test
tests/test_contamination_tech_reps.nf.test.snap
tests/test_mirgenedb.nf.test
tests/test_mirgenedb.nf.test.snap
tests/test_nextflex.nf.test
tests/test_nextflex.nf.test.snap
tests/test_skipfastp.nf.test
tests/test_skipfastp.nf.test.snap
tests/test_umi.nf.test
tests/test_umi.nf.test.snap

PoC: Pivot tables to improve processing of large files. 
#484 
- Pivot longer, concat and pivot wider:1000 files (30000 rows each).  (duration: 35m 35s)

Replace `CSVTK_JOIN` to improve processing in large amount of files
